### ISSUE TITLE
Hex colour support

### ISSUE THREAD

**Issue by BumbleTree** [DailyStruggle/OnePlayerSleep#16]
I am losing my mind over these rainbow messages and hard coding them into the config would be possible and great if the plugin supported hex colours
Please allow the plugin to show hex colours with the format &# in the messages yml

**Comment by DailyStruggle** [comment]
this may or may not be impossible for me to do while including hover and click events. 

My first attempt is a complete failure because of the hard limits of the Player.spigot().sendMessage method in the Spigot API. Unlike the Player.sendMessage(String) method, it only reads colors one character at a time, so hex values boil down to just the last character. I'm not aware of another way to add hover or click events, so I'm stuck.
